import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

interface AbiItem { type: string; name?: string; [key: string]: unknown }

// What the liquidation bot reads from each Farmenta contract. `names` keeps the items with that
// name (every overload), `kinds` keeps every item of that type.
const SELECTION: { exportName: string; artifact: string; names?: string[]; kinds?: string[] }[] = [
  { exportName: 'marketAbi', artifact: 'FarmentaMarket.sol/FarmentaMarket.json', names: ['asset', 'debtOf', 'loanOf', 'Liquidate'] },
  { exportName: 'lensAbi', artifact: 'MarketLens.sol/MarketLens.json', names: ['liquidationHealthFactor', 'liquidationCloseFactorBps'] },
  { exportName: 'policyAbi', artifact: 'CollateralPolicy.sol/CollateralPolicy.json', names: ['listingOf'] },
  { exportName: 'recorderAbi', artifact: 'TwapRecorder.sol/TwapRecorder.json', names: ['consult', 'record', 'TwapUnavailable'] },
  { exportName: 'helperAbi', artifact: 'LiquidatorHelper.sol/LiquidatorHelper.json', names: ['execute'], kinds: ['error'] },
  // `liquidate` runs in the linked library, so its errors are in the library's ABI, not the market's.
  { exportName: 'liquidationErrorsAbi', artifact: 'MarketLiquidation.sol/MarketLiquidation.json', kinds: ['error'] },
];

function withoutInternalTypes(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(withoutInternalTypes);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(Object.entries(value).filter(([key]) => key !== 'internalType').map(([key, entry]) => [key, withoutInternalTypes(entry)]));
}

/** The source of `src/contract-abi.ts` for the forge artifacts under `contractsDir/out`. */
export async function renderContractAbi(contractsDir: string, commit: string): Promise<string> {
  const lines = [
    '// Generated by `bun run abi:generate` from the forge artifacts of farmenta-defi/smart-contract',
    `// at ${commit} (contracts/source.json). Do not edit by hand: a signature typed from memory`,
    '// decodes nothing and fails silently. `bun run test:fork` fails when this file is out of date.',
    '',
  ];
  for (const { exportName, artifact, names = [], kinds = [] } of SELECTION) {
    const { abi } = JSON.parse(await readFile(join(contractsDir, 'out', artifact), 'utf8')) as { abi: AbiItem[] };
    const items = abi.filter((item) => (item.name !== undefined && names.includes(item.name)) || kinds.includes(item.type));
    const missing = names.filter((name) => !items.some((item) => item.name === name));
    if (missing.length > 0) throw new Error(`${artifact} has no ${missing.join(', ')}`);
    lines.push(`export const ${exportName} = [`);
    for (const item of items) lines.push(`  ${JSON.stringify(withoutInternalTypes(item))},`);
    lines.push('] as const;', '');
  }
  return lines.join('\n');
}
