// Generated by `bun run abi:generate` from the forge artifacts of farmenta-defi/smart-contract
// at f038274f4ddf030135d11adc3d2ca144802f8cbf (contracts/source.json). Do not edit by hand: a signature typed from memory
// decodes nothing and fails silently. `bun run test:fork` fails when this file is out of date.

export const marketAbi = [
  {"type":"function","name":"asset","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"debtOf","inputs":[{"name":"tokenId","type":"uint256"}],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"loanOf","inputs":[{"name":"tokenId","type":"uint256"}],"outputs":[{"name":"","type":"tuple","components":[{"name":"owner","type":"address"},{"name":"tier","type":"uint8"},{"name":"debtShares","type":"uint256"},{"name":"poolKeyId","type":"bytes32"}]}],"stateMutability":"view"},
  {"type":"event","name":"Liquidate","inputs":[{"name":"tokenId","type":"uint256","indexed":true},{"name":"liquidator","type":"address","indexed":true},{"name":"poolId","type":"bytes32","indexed":true},{"name":"repaid","type":"uint256","indexed":false},{"name":"out0","type":"uint256","indexed":false},{"name":"out1","type":"uint256","indexed":false},{"name":"badDebt","type":"uint256","indexed":false},{"name":"fullSeizure","type":"bool","indexed":false}],"anonymous":false},
] as const;

export const lensAbi = [
  {"type":"function","name":"liquidationCloseFactorBps","inputs":[{"name":"tokenId","type":"uint256"}],"outputs":[{"name":"","type":"uint16"}],"stateMutability":"view"},
  {"type":"function","name":"liquidationHealthFactor","inputs":[{"name":"tokenId","type":"uint256"}],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
] as const;

export const policyAbi = [
  {"type":"function","name":"listingOf","inputs":[{"name":"poolId","type":"bytes32"}],"outputs":[{"name":"","type":"tuple","components":[{"name":"listed","type":"bool"},{"name":"frozen","type":"bool"},{"name":"tier","type":"uint8"},{"name":"maxLtvBps","type":"uint16"},{"name":"ltStartBps","type":"uint16"},{"name":"ltTargetBps","type":"uint16"},{"name":"rampStart","type":"uint40"},{"name":"rampDuration","type":"uint40"},{"name":"liquidatorBonusBps","type":"uint16"},{"name":"removeHaircutBps","type":"uint16"},{"name":"debtCapUsdg","type":"uint128"},{"name":"minPositionUsd","type":"uint128"}]}],"stateMutability":"view"},
] as const;

export const recorderAbi = [
  {"type":"function","name":"consult","inputs":[{"name":"poolId","type":"bytes32"},{"name":"window","type":"uint32"}],"outputs":[{"name":"","type":"int24"}],"stateMutability":"view"},
  {"type":"function","name":"consult","inputs":[{"name":"poolId","type":"bytes32"}],"outputs":[{"name":"","type":"int24"}],"stateMutability":"view"},
  {"type":"function","name":"record","inputs":[{"name":"key","type":"tuple","components":[{"name":"currency0","type":"address"},{"name":"currency1","type":"address"},{"name":"fee","type":"uint24"},{"name":"tickSpacing","type":"int24"},{"name":"hooks","type":"address"}]}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"error","name":"TwapUnavailable","inputs":[]},
] as const;

export const helperAbi = [
  {"type":"function","name":"execute","inputs":[{"name":"tokenId","type":"uint256"},{"name":"repayAmount","type":"uint256"},{"name":"swapCalldata","type":"bytes"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"error","name":"ResidualBalance","inputs":[{"name":"token","type":"address"},{"name":"balance","type":"uint256"}]},
  {"type":"error","name":"SafeERC20FailedOperation","inputs":[{"name":"token","type":"address"}]},
  {"type":"error","name":"SwapFailed","inputs":[{"name":"reason","type":"bytes"}]},
  {"type":"error","name":"UnauthorizedMorpho","inputs":[{"name":"caller","type":"address"}]},
  {"type":"error","name":"ZeroRepayAmount","inputs":[]},
] as const;

export const liquidationErrorsAbi = [
  {"type":"error","name":"FeePurchaseUnderfunded","inputs":[{"name":"required","type":"uint256"},{"name":"available","type":"uint256"}]},
  {"type":"error","name":"InvalidRecipient","inputs":[{"name":"to","type":"address"}]},
  {"type":"error","name":"NothingToRepay","inputs":[{"name":"tokenId","type":"uint256"}]},
  {"type":"error","name":"PositionIsHealthy","inputs":[{"name":"tokenId","type":"uint256"},{"name":"healthFactor","type":"uint256"}]},
  {"type":"error","name":"PositionNotCollateral","inputs":[{"name":"tokenId","type":"uint256"}]},
  {"type":"error","name":"SafeERC20FailedOperation","inputs":[{"name":"token","type":"address"}]},
  {"type":"error","name":"SeizureBelowMinimum","inputs":[{"name":"out0","type":"uint256"},{"name":"out1","type":"uint256"}]},
] as const;
